In [11]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, scale
from sklearn.model_selection import train_test_split

In [12]:
from sklearn.datasets import load_breast_cancer

# Carregar o conjunto de dados
data = load_breast_cancer()

# Acessar os dados e os rótulos
X: np.ndarray = data.data #type: ignore
y: np.ndarray = data.target #type: ignore

In [13]:
X

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [14]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [15]:
# Normalizar os dados
scaler = MinMaxScaler()
scaler.fit(X)
X = scaler.transform(X)
X

array([[0.52103744, 0.0226581 , 0.54598853, ..., 0.91202749, 0.59846245,
        0.41886396],
       [0.64314449, 0.27257355, 0.61578329, ..., 0.63917526, 0.23358959,
        0.22287813],
       [0.60149557, 0.3902604 , 0.59574321, ..., 0.83505155, 0.40370589,
        0.21343303],
       ...,
       [0.45525108, 0.62123774, 0.44578813, ..., 0.48728522, 0.12872068,
        0.1519087 ],
       [0.64456434, 0.66351031, 0.66553797, ..., 0.91065292, 0.49714173,
        0.45231536],
       [0.03686876, 0.50152181, 0.02853984, ..., 0.        , 0.25744136,
        0.10068215]])

In [16]:
# Dividir os dados em treino e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [17]:
data['filename']

'breast_cancer.csv'

In [18]:
feature_names = data.feature_names # type: ignore
feature_names


array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [21]:
len(feature_names)

30

In [19]:
data_train = pd.DataFrame(X_train, columns=feature_names)
data_train['target'] = y_train
data_test = pd.DataFrame(X_test, columns=feature_names)
data_test['target'] = y_test
data_test

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0       0.259785      0.300643        0.257757   0.143542         0.424483   
1       0.565999      0.392289        0.551517   0.418452         0.338178   
2       0.401297      0.330402        0.400180   0.256797         0.510698   
3       0.256472      0.269530        0.260383   0.137561         0.476393   
4       0.215770      0.159959        0.213254   0.110032         0.426198   
..           ...           ...             ...        ...              ...   
109     0.362488      0.241461        0.348421   0.221633         0.304956   
110     0.430167      0.336152        0.416765   0.285981         0.352532   
111     0.214823      0.176530        0.207864   0.111474         0.439379   
112     0.342610      0.613460        0.336950   0.203775         0.267220   
113     0.650717      0.724045        0.635132   0.541039         0.379706   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0            0.265076        0.187559             0.189911       0.436869   
1            0.256181        0.253046             0.395179       0.263636   
2            0.315686        0.343486             0.401938       0.439899   
3            0.344212        0.181373             0.139115       0.379293   
4            0.284093        0.157849             0.128926       0.382828   
..                ...             ...                  ...            ...   
109          0.146003        0.121649             0.138718       0.176263   
110          0.198945        0.228889             0.329920       0.372727   
111          0.180050        0.101406             0.145577       0.415657   
112          0.259248        0.258435             0.219085       0.142424   
113          0.291148        0.320291             0.429722       0.358081   

     mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                  0.290017  ...       0.336354         0.227302    0.121092   
1                  0.097936  ...       0.388060         0.575178    0.413095   
2                  0.168492  ...       0.372601         0.370985    0.238596   
3                  0.443555  ...       0.290245         0.195229    0.081252   
4                  0.376158  ...       0.204158         0.141292    0.066998   
..                      ...  ...            ...              ...         ...   
109                0.075611  ...       0.357676         0.276856    0.158720   
110                0.083193  ...       0.334222         0.390408    0.255063   
111                0.246841  ...       0.244403         0.151751    0.075354   
112                0.238627  ...       0.760128         0.259425    0.142253   
113                0.142797  ...       0.936567         0.814732    0.797975   

     worst smoothness  worst compactness  worst concavity  \
0            0.471703           0.204238         0.213339   
1            0.317837           0.200163         0.214617   
2            0.550948           0.205790         0.302796   
3            0.487552           0.228590         0.191933   
4            0.418213           0.179013         0.143530   
..                ...                ...              ...   
109          0.284158           0.174356         0.194649   
110          0.520571           0.171930         0.225958   
111          0.447269           0.127010         0.144089   
112          0.243875           0.208895         0.244728   
113          0.455194           0.230045         0.274920   

     worst concave points  worst symmetry  worst fractal dimension  target  
0                0.348797        0.285630                 0.212908       1  
1                0.614777        0.194362                 0.071166       0  
2                0.520275        0.250739                 0.164961       0  
3                0.253265        0.195348                 0.252853       1  
4                0.237732        0.150601                 0.1725

In [20]:
# exportar dados 
data_train.to_csv('data_train.csv', index=False)
data_test.to_csv('data_test.csv', index=False)
data = pd.concat([data_train, data_test])
data.to_csv('data.csv', index=False)